all:
	gcc -o exe main.c #-std=c11 -_XOPEN_SOURCE
	gcc -o cexe mainc.c #-std=c11 -_XOPEN_SOURCE
rm:
	rm -rf *.o exe
cl:
	gcc -o cexe mainc.c #-std=c11 -_XOPEN_SOURCE
se:
	gcc -o exe main.c #-std=c11 -_XOPEN_SOURCE

